config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true

  CUTENESS_OPTIONS = %w[Sweet Lovely Adorable Precious Purrfection].freeze
  validates :cuteness, inclusion: { in: CUTENESS_OPTIONS }

  SOFTNESS_OPTIONS = %w[Smooth Fluffy Fuzzy Silky Cloudlike].freeze
  validates :softness, inclusion: { in: SOFTNESS_OPTIONS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten, notice: 'Successfully created a new Kitten!'
    else
      render 'new', notice: 'Failed to create Kitten'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    # no need for a instance variable a local one will suffice since this method will never be rendered, ir is only patch /put to the db
    kitten = Kitten.find(params[:id])
    kitten.update!(kitten_params)

    redirect_to kitten
  end

  def destroy
    kitten = Kitten.find(params[:id])
    kitten.destroy!

    redirect_to kittens_path, notice: 'The kitten was erased (:sad)'
  end

  private

  def kitten_params
    params.expect(kitten: %i[name age cuteness softness])
    # https://dev.to/jessalejo/comparing-paramsexpect-to-paramsrequire-and-paramsfetch-5a69
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kittens/_form.html.erb
<%= form_with model:@kitten do |form| %>
    <%=form.label :name, "Kitten Name:"%>
    <%=form.text_field :name%>

    <%=form.label :age, "Kitten Age:"%>
    <%=form.number_field :age%>

    <%=form.label :cuteness, "Kitten cuteness:"%>
    <%=form.select :cuteness, options_for_select(Kitten::CUTENESS_OPTIONS)%>

    <%=form.label :softness, "Kitten softness:"%>
    <%=form.select :softness, options_for_select(Kitten::SOFTNESS_OPTIONS)%>

    <%= form.submit%>
<%end%>

app/views/kittens/_kitten.html.erb
<div>
   <ul class="list">
      <li>
         <h3>Name:</h3>
         <div><%=kitten.name%></div>
      </li>

    <%if kitten.age.present?%>
      <li>
         <h3>Age:</h3>
         <div><%=kitten.age%></div>
      </li> 
    <%end%>

    <%if kitten.cuteness.present?%>
      <li>
         <h3>Cuteness:</h3>
         <div><%=kitten.cuteness%></div>
      </li>
    <%end%>

    <%if kitten.softness.present?%>
      <li>
        <h3>Softness:</h3>
        <div><%=kitten.softness%></div>
      </li>
    <%end%>
   </ul>
</div>

app/views/kittens/edit.html.erb
<h1>kittens#edit</h1>
<p>Find me in app/views/kittens/edit.html.erb</p>
<%= link_to "Main Page", kittens_path%>

<h2>Edit Kitten</h2>
<%=render "form"%>

app/views/kittens/index.html.erb
<h1>kittens#index</h1>
<p>Find me in app/views/kittens/index.html.erb</p>

<%=link_to "Add Kitten", new_kitten_path%>

<%@kittens.each_with_index do |kitten, index|%>
    <div><h2>Kitten nº <%=(index+1).to_s.rjust(3,"0")%></h2></div>
    <%= render kitten%>
    
    <div><%= link_to "See Profile", kitten%> | <%= link_to "Edit Kitten", edit_kitten_path(kitten) %></div>
<%end%>

app/views/kittens/new.html.erb
<h1>kittens#new</h1>
<p>Find me in app/views/kittens/new.html.erb</p>
<%= link_to "Main Page", kittens_path%>

<h2>Create new Kitten</h2>
<%=render "form"%>

app/views/kittens/show.html.erb
<h1>kittens#show</h1>
<p>Find me in app/views/kittens/show.html.erb</p>
<%= link_to "Main Page", kittens_path%>


<%= render @kitten%>
<div>
    <%=link_to "Edit Kitten", edit_kitten_path(@kitten)%>
    <%= button_to "Delete Kitten", @kitten, method: :delete%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>